// ─── Clinic ────────────────────────────────────────────────────────────────
export const clinic = {
  id: "clinic-001",
  name: "MediCare Plus",
  tagline: "Advanced Clinical Management",
  address: "42 Healthcare Ave, Mumbai 400001",
  phone: "+91 22 4567 8900",
  email: "care@medicareplus.in",
  logoUrl: null,
  primaryColor: "#00d4ff",
};

// ─── Specializations ────────────────────────────────────────────────────────
export const specializations = [
  { id: "spec-001", name: "General Medicine", clinicId: "clinic-001" },
  { id: "spec-002", name: "Cardiology", clinicId: "clinic-001" },
  { id: "spec-003", name: "Pediatrics", clinicId: "clinic-001" },
  { id: "spec-004", name: "Orthopedics", clinicId: "clinic-001" },
  { id: "spec-005", name: "Neurology", clinicId: "clinic-001" },
];

// ─── Doctors ────────────────────────────────────────────────────────────────
export const doctors = [
  {
    id: "doctor-001",
    name: "Dr. Sarah Chen",
    phone: "9000000001",
    specialization: "Cardiology",
    specializationId: "spec-002",
    qualification: "MBBS, MD (Cardiology), FACC",
    experience: 14,
    consultationFee: 800,
    bio: "Specialist in interventional cardiology and heart failure management. Over 14 years of experience.",
    isActive: true,
    clinicId: "clinic-001",
    avatarUrl: null,
    schedule: [
      { dayOfWeek: 1, startTime: "09:00", endTime: "13:00", slotDurationMinutes: 15, isActive: true },
      { dayOfWeek: 2, startTime: "09:00", endTime: "13:00", slotDurationMinutes: 15, isActive: true },
      { dayOfWeek: 3, startTime: "14:00", endTime: "18:00", slotDurationMinutes: 15, isActive: true },
      { dayOfWeek: 4, startTime: "09:00", endTime: "13:00", slotDurationMinutes: 15, isActive: true },
      { dayOfWeek: 5, startTime: "09:00", endTime: "12:00", slotDurationMinutes: 15, isActive: true },
    ],
    todayStats: { total: 18, completed: 12, waiting: 4, inProgress: 1 },
  },
  {
    id: "doctor-002",
    name: "Dr. Raj Patel",
    phone: "9000000002",
    specialization: "General Medicine",
    specializationId: "spec-001",
    qualification: "MBBS, DNB (Family Medicine)",
    experience: 9,
    consultationFee: 500,
    bio: "Comprehensive primary care physician with expertise in preventive medicine and chronic disease management.",
    isActive: true,
    clinicId: "clinic-001",
    avatarUrl: null,
    schedule: [
      { dayOfWeek: 1, startTime: "09:00", endTime: "17:00", slotDurationMinutes: 10, isActive: true },
      { dayOfWeek: 2, startTime: "09:00", endTime: "17:00", slotDurationMinutes: 10, isActive: true },
      { dayOfWeek: 3, startTime: "09:00", endTime: "17:00", slotDurationMinutes: 10, isActive: true },
      { dayOfWeek: 4, startTime: "09:00", endTime: "17:00", slotDurationMinutes: 10, isActive: true },
      { dayOfWeek: 6, startTime: "09:00", endTime: "13:00", slotDurationMinutes: 10, isActive: true },
    ],
    todayStats: { total: 24, completed: 18, waiting: 5, inProgress: 1 },
  },
  {
    id: "doctor-003",
    name: "Dr. Maya Johnson",
    phone: "9000000004",
    specialization: "Pediatrics",
    specializationId: "spec-003",
    qualification: "MBBS, MD (Pediatrics), IAP Fellowship",
    experience: 11,
    consultationFee: 600,
    bio: "Dedicated pediatrician with special interest in developmental pediatrics and neonatal care.",
    isActive: true,
    clinicId: "clinic-001",
    avatarUrl: null,
    schedule: [
      { dayOfWeek: 1, startTime: "10:00", endTime: "14:00", slotDurationMinutes: 20, isActive: true },
      { dayOfWeek: 2, startTime: "10:00", endTime: "14:00", slotDurationMinutes: 20, isActive: true },
      { dayOfWeek: 3, startTime: "15:00", endTime: "19:00", slotDurationMinutes: 20, isActive: true },
      { dayOfWeek: 5, startTime: "10:00", endTime: "14:00", slotDurationMinutes: 20, isActive: true },
    ],
    todayStats: { total: 12, completed: 8, waiting: 3, inProgress: 1 },
  },
];

// ─── Patients ────────────────────────────────────────────────────────────────
export const patients = [
  {
    id: "patient-001",
    name: "Arjun Sharma",
    phone: "9876543210",
    email: "arjun@example.com",
    dateOfBirth: "1985-06-15",
    age: 40,
    gender: "Male",
    bloodGroup: "B+",
    address: "12 Rose Garden, Andheri West, Mumbai",
    clinicId: "clinic-001",
    allergies: [{ id: "alg-1", allergen: "Penicillin", reaction: "Rash", severity: "Moderate" }],
    activeMedications: [{ id: "med-1", name: "Atorvastatin 10mg", dosage: "1-0-0", startDate: "2024-01-01" }],
    medicalHistory: "Hypertension, managed with diet and exercise. Family history of diabetes.",
  },
  {
    id: "patient-002",
    name: "Priya Nair",
    phone: "9876543211",
    email: "priya@example.com",
    dateOfBirth: "1992-03-22",
    age: 33,
    gender: "Female",
    bloodGroup: "O+",
    address: "5B Palm Beach Rd, Navi Mumbai",
    clinicId: "clinic-001",
    allergies: [],
    activeMedications: [],
    medicalHistory: "No significant medical history.",
  },
  {
    id: "patient-003",
    name: "Kiran Mehta",
    phone: "9876543212",
    email: "kiran@example.com",
    dateOfBirth: "1978-11-08",
    age: 47,
    gender: "Male",
    bloodGroup: "A-",
    address: "Tower C, Skyline Apt, Powai",
    clinicId: "clinic-001",
    allergies: [{ id: "alg-2", allergen: "Sulfa drugs", reaction: "Anaphylaxis", severity: "Severe" }],
    activeMedications: [
      { id: "med-2", name: "Metformin 500mg", dosage: "1-0-1", startDate: "2023-05-10" },
      { id: "med-3", name: "Amlodipine 5mg", dosage: "0-0-1", startDate: "2023-05-10" },
    ],
    medicalHistory: "Type 2 Diabetes (2020), Hypertension (2018).",
  },
  {
    id: "patient-004",
    name: "Sunita Verma",
    phone: "9876543213",
    email: "sunita@example.com",
    dateOfBirth: "2018-04-12",
    age: 7,
    gender: "Female",
    bloodGroup: "B-",
    address: "47 Saraswati Nagar, Pune",
    clinicId: "clinic-001",
    allergies: [],
    activeMedications: [],
    medicalHistory: "Recurrent ear infections.",
  },
  {
    id: "patient-005",
    name: "Rahul Desai",
    phone: "9876543214",
    email: "rahul@example.com",
    dateOfBirth: "1960-09-25",
    age: 64,
    gender: "Male",
    bloodGroup: "AB+",
    address: "22 Lotus Colony, Thane West",
    clinicId: "clinic-001",
    allergies: [{ id: "alg-3", allergen: "NSAIDs", reaction: "GI Bleed", severity: "Severe" }],
    activeMedications: [
      { id: "med-4", name: "Warfarin 5mg", dosage: "0-0-1", startDate: "2022-02-14" },
      { id: "med-5", name: "Carvedilol 12.5mg", dosage: "1-0-1", startDate: "2022-02-14" },
    ],
    medicalHistory: "Atrial fibrillation (2022), Congestive Heart Failure (2022). Former smoker.",
  },
  {
    id: "patient-006",
    name: "Deepa Krishnan",
    phone: "9876543215",
    email: "deepa@example.com",
    dateOfBirth: "1998-12-03",
    age: 27,
    gender: "Female",
    bloodGroup: "O-",
    address: "Flat 801, Orchid Heights, Bandra",
    clinicId: "clinic-001",
    allergies: [],
    activeMedications: [],
    medicalHistory: "Seasonal allergic rhinitis.",
  },
];

// ─── Appointments ─────────────────────────────────────────────────────────────
const today = new Date().toISOString().split("T")[0];
export const appointments = [
  {
    id: "appt-001",
    patientId: "patient-001",
    patientName: "Arjun Sharma",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    slotStart: `${today}T09:00:00`,
    slotEnd: `${today}T09:15:00`,
    status: "Scheduled",
    source: "Online",
    clinicId: "clinic-001",
    notes: "Follow-up for ECG results",
  },
  {
    id: "appt-002",
    patientId: "patient-002",
    patientName: "Priya Nair",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    slotStart: `${today}T09:15:00`,
    slotEnd: `${today}T09:30:00`,
    status: "Completed",
    source: "Online",
    clinicId: "clinic-001",
    notes: "Chest pain evaluation",
  },
  {
    id: "appt-003",
    patientId: "patient-003",
    patientName: "Kiran Mehta",
    doctorId: "doctor-002",
    doctorName: "Dr. Raj Patel",
    slotStart: `${today}T10:00:00`,
    slotEnd: `${today}T10:10:00`,
    status: "Scheduled",
    source: "WalkIn",
    clinicId: "clinic-001",
    notes: "Diabetes follow-up",
  },
  {
    id: "appt-004",
    patientId: "patient-004",
    patientName: "Sunita Verma",
    doctorId: "doctor-003",
    doctorName: "Dr. Maya Johnson",
    slotStart: `${today}T10:20:00`,
    slotEnd: `${today}T10:40:00`,
    status: "Scheduled",
    source: "Online",
    clinicId: "clinic-001",
    notes: "Ear pain follow-up",
  },
  {
    id: "appt-005",
    patientId: "patient-005",
    patientName: "Rahul Desai",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    slotStart: `${today}T11:00:00`,
    slotEnd: `${today}T11:15:00`,
    status: "Scheduled",
    source: "Online",
    clinicId: "clinic-001",
    notes: "Heart failure monitoring",
  },
  {
    id: "appt-006",
    patientId: "patient-006",
    patientName: "Deepa Krishnan",
    doctorId: "doctor-002",
    doctorName: "Dr. Raj Patel",
    slotStart: `${today}T11:30:00`,
    slotEnd: `${today}T11:40:00`,
    status: "Cancelled",
    source: "Online",
    clinicId: "clinic-001",
    notes: "",
  },
];

// ─── Tokens (Live Queue) ─────────────────────────────────────────────────────
export type TokenStatus = "Waiting" | "Arrived" | "Called" | "OnHold" | "Skipped" | "Completed" | "Abandoned";

export interface Token {
  id: string;
  tokenNumber: number;
  patientId: string;
  patientName: string;
  patientPhone: string;
  doctorId: string;
  doctorName: string;
  queueDate: string;
  status: TokenStatus;
  source: "Online" | "WalkIn";
  appointmentId?: string;
  visitId?: string;
  createdAt: string;
  calledAt?: string;
}

export const initialTokens: Token[] = [
  {
    id: "tok-001",
    tokenNumber: 1,
    patientId: "patient-002",
    patientName: "Priya Nair",
    patientPhone: "9876543211",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    queueDate: today,
    status: "Completed",
    source: "Online",
    appointmentId: "appt-002",
    visitId: "visit-001",
    createdAt: `${today}T08:00:00`,
    calledAt: `${today}T09:05:00`,
  },
  {
    id: "tok-002",
    tokenNumber: 2,
    patientId: "patient-001",
    patientName: "Arjun Sharma",
    patientPhone: "9876543210",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    queueDate: today,
    status: "Called",
    source: "Online",
    appointmentId: "appt-001",
    visitId: "visit-002",
    createdAt: `${today}T08:05:00`,
    calledAt: `${today}T09:20:00`,
  },
  {
    id: "tok-003",
    tokenNumber: 3,
    patientId: "patient-005",
    patientName: "Rahul Desai",
    patientPhone: "9876543214",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    queueDate: today,
    status: "Arrived",
    source: "Online",
    appointmentId: "appt-005",
    createdAt: `${today}T08:30:00`,
  },
  {
    id: "tok-004",
    tokenNumber: 4,
    patientId: "patient-006",
    patientName: "Deepa Krishnan",
    patientPhone: "9876543215",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    queueDate: today,
    status: "Waiting",
    source: "WalkIn",
    createdAt: `${today}T09:45:00`,
  },
  {
    id: "tok-005",
    tokenNumber: 5,
    patientId: "patient-003",
    patientName: "Kiran Mehta",
    patientPhone: "9876543212",
    doctorId: "doctor-002",
    doctorName: "Dr. Raj Patel",
    queueDate: today,
    status: "Called",
    source: "Online",
    appointmentId: "appt-003",
    visitId: "visit-003",
    createdAt: `${today}T09:00:00`,
    calledAt: `${today}T10:05:00`,
  },
  {
    id: "tok-006",
    tokenNumber: 6,
    patientId: "patient-004",
    patientName: "Sunita Verma",
    patientPhone: "9876543213",
    doctorId: "doctor-003",
    doctorName: "Dr. Maya Johnson",
    queueDate: today,
    status: "Waiting",
    source: "Online",
    appointmentId: "appt-004",
    createdAt: `${today}T09:30:00`,
  },
  {
    id: "tok-007",
    tokenNumber: 7,
    patientId: "patient-002",
    patientName: "Priya Nair",
    patientPhone: "9876543211",
    doctorId: "doctor-002",
    doctorName: "Dr. Raj Patel",
    queueDate: today,
    status: "OnHold",
    source: "WalkIn",
    createdAt: `${today}T10:15:00`,
  },
  {
    id: "tok-008",
    tokenNumber: 8,
    patientId: "patient-001",
    patientName: "Arjun Sharma",
    patientPhone: "9876543210",
    doctorId: "doctor-002",
    doctorName: "Dr. Raj Patel",
    queueDate: today,
    status: "Skipped",
    source: "Online",
    createdAt: `${today}T10:30:00`,
  },
];

// ─── Visits ────────────────────────────────────────────────────────────────────
export const visits = [
  {
    id: "visit-001",
    patientId: "patient-002",
    patientName: "Priya Nair",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    tokenId: "tok-001",
    appointmentId: "appt-002",
    status: "Completed",
    clinicId: "clinic-001",
    startedAt: `${today}T09:05:00`,
    completedAt: `${today}T09:18:00`,
    version: 2,
    prescription: {
      id: "rx-001",
      diagnosis: "Musculoskeletal chest pain",
      vitals: { bp: "118/76", pulse: 72, temp: 98.6, weight: 58, spo2: 99 },
      medicines: [
        { name: "Ibuprofen 400mg", dosage: "1-1-1", duration: "5 days", instructions: "After food" },
        { name: "Pan-D capsule", dosage: "1-0-0", duration: "5 days", instructions: "Before breakfast" },
      ],
      advice: "Rest, avoid heavy lifting. Warm compress to chest.",
      followUpDate: "2025-07-27",
      pdfUrl: "https://example.com/rx/rx-001.pdf",
      createdAt: `${today}T09:18:00`,
    },
  },
  {
    id: "visit-002",
    patientId: "patient-001",
    patientName: "Arjun Sharma",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    tokenId: "tok-002",
    appointmentId: "appt-001",
    status: "Open",
    clinicId: "clinic-001",
    startedAt: `${today}T09:20:00`,
    version: 1,
    draft: {
      chiefComplaint: "Palpitations and mild shortness of breath",
      symptoms: ["Palpitations", "Mild dyspnea on exertion", "Occasional chest discomfort"],
      vitals: { bp: "138/88", pulse: 92, temp: 98.4, weight: 78, spo2: 97 },
      examination: "Regular heart rate, mild irregularity noted. No murmurs. Lungs clear.",
      diagnosis: "Hypertensive heart disease — under evaluation",
      investigations: ["ECG", "2D Echo", "Lipid profile", "HbA1c"],
      medicines: [],
      advice: "",
      followUpDate: "",
    },
  },
];

// ─── Prescriptions ────────────────────────────────────────────────────────────
export const prescriptions = [
  {
    id: "rx-001",
    visitId: "visit-001",
    patientId: "patient-002",
    patientName: "Priya Nair",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    diagnosis: "Musculoskeletal chest pain",
    medicines: [
      { name: "Ibuprofen 400mg", dosage: "1-1-1", duration: "5 days", instructions: "After food" },
      { name: "Pan-D capsule", dosage: "1-0-0", duration: "5 days", instructions: "Before breakfast" },
    ],
    advice: "Rest, avoid heavy lifting. Warm compress to chest.",
    followUpDate: "2025-07-27",
    pdfUrl: "https://example.com/rx/rx-001.pdf",
    createdAt: `${today}T09:18:00`,
    clinicId: "clinic-001",
  },
  {
    id: "rx-hist-001",
    visitId: "visit-hist-001",
    patientId: "patient-001",
    patientName: "Arjun Sharma",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    diagnosis: "Hypertension — routine follow-up",
    medicines: [
      { name: "Telmisartan 40mg", dosage: "1-0-0", duration: "30 days", instructions: "Morning" },
    ],
    advice: "Low-salt diet. Daily 30-min walk. Monitor BP at home.",
    followUpDate: "2025-06-20",
    pdfUrl: "https://example.com/rx/rx-hist-001.pdf",
    createdAt: "2025-05-20T10:30:00",
    clinicId: "clinic-001",
  },
  {
    id: "rx-hist-002",
    visitId: "visit-hist-002",
    patientId: "patient-001",
    patientName: "Arjun Sharma",
    doctorId: "doctor-002",
    doctorName: "Dr. Raj Patel",
    diagnosis: "Viral upper respiratory tract infection",
    medicines: [
      { name: "Paracetamol 650mg", dosage: "1-1-1", duration: "5 days", instructions: "As needed for fever" },
      { name: "Cetirizine 10mg", dosage: "0-0-1", duration: "5 days", instructions: "At bedtime" },
    ],
    advice: "Plenty of fluids, rest.",
    followUpDate: "",
    pdfUrl: "https://example.com/rx/rx-hist-002.pdf",
    createdAt: "2025-03-10T11:00:00",
    clinicId: "clinic-001",
  },
];

// ─── Invoices ─────────────────────────────────────────────────────────────────
export const invoices = [
  {
    id: "inv-001",
    patientId: "patient-002",
    patientName: "Priya Nair",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    visitId: "visit-001",
    items: [
      { description: "Consultation Fee", amount: 800 },
      { description: "ECG", amount: 400 },
    ],
    subtotal: 1200,
    tax: 0,
    total: 1200,
    status: "Paid",
    paymentMethod: "UPI",
    paidAt: `${today}T09:25:00`,
    createdAt: `${today}T09:20:00`,
    clinicId: "clinic-001",
  },
  {
    id: "inv-002",
    patientId: "patient-003",
    patientName: "Kiran Mehta",
    doctorId: "doctor-002",
    doctorName: "Dr. Raj Patel",
    visitId: "visit-003",
    items: [
      { description: "Consultation Fee", amount: 500 },
      { description: "Blood Glucose (Fasting)", amount: 150 },
      { description: "HbA1c", amount: 350 },
    ],
    subtotal: 1000,
    tax: 0,
    total: 1000,
    status: "Pending",
    paymentMethod: null,
    paidAt: null,
    createdAt: `${today}T10:05:00`,
    clinicId: "clinic-001",
  },
  {
    id: "inv-003",
    patientId: "patient-001",
    patientName: "Arjun Sharma",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    visitId: "visit-002",
    items: [
      { description: "Consultation Fee", amount: 800 },
      { description: "ECG", amount: 400 },
      { description: "2D Echo", amount: 1500 },
    ],
    subtotal: 2700,
    tax: 0,
    total: 2700,
    status: "Pending",
    paymentMethod: null,
    paidAt: null,
    createdAt: `${today}T09:20:00`,
    clinicId: "clinic-001",
  },
  {
    id: "inv-hist-001",
    patientId: "patient-001",
    patientName: "Arjun Sharma",
    doctorId: "doctor-001",
    doctorName: "Dr. Sarah Chen",
    visitId: "visit-hist-001",
    items: [{ description: "Consultation Fee", amount: 800 }],
    subtotal: 800,
    tax: 0,
    total: 800,
    status: "Paid",
    paymentMethod: "Cash",
    paidAt: "2025-05-20T11:00:00",
    createdAt: "2025-05-20T10:35:00",
    clinicId: "clinic-001",
  },
];

// ─── Audit Log ────────────────────────────────────────────────────────────────
export const auditLogs = [
  {
    id: "aud-001",
    action: "TOKEN_CALLED",
    entityType: "Token",
    entityId: "tok-002",
    performedBy: "receptionist-001",
    performedByName: "Raj (Receptionist)",
    description: "Called token #2 for Arjun Sharma → Dr. Sarah Chen",
    createdAt: `${today}T09:20:00`,
    clinicId: "clinic-001",
  },
  {
    id: "aud-002",
    action: "VISIT_STARTED",
    entityType: "Visit",
    entityId: "visit-002",
    performedBy: "doctor-001",
    performedByName: "Dr. Sarah Chen",
    description: "Started consultation for Arjun Sharma",
    createdAt: `${today}T09:22:00`,
    clinicId: "clinic-001",
  },
  {
    id: "aud-003",
    action: "INVOICE_PAID",
    entityType: "Invoice",
    entityId: "inv-001",
    performedBy: "receptionist-001",
    performedByName: "Raj (Receptionist)",
    description: "Marked Invoice #inv-001 as Paid — ₹1,200 via UPI",
    createdAt: `${today}T09:25:00`,
    clinicId: "clinic-001",
  },
  {
    id: "aud-004",
    action: "WALKIN_REGISTERED",
    entityType: "Token",
    entityId: "tok-004",
    performedBy: "receptionist-001",
    performedByName: "Raj (Receptionist)",
    description: "Walk-in registered for Deepa Krishnan",
    createdAt: `${today}T09:45:00`,
    clinicId: "clinic-001",
  },
  {
    id: "aud-005",
    action: "TOKEN_HOLD",
    entityType: "Token",
    entityId: "tok-007",
    performedBy: "receptionist-001",
    performedByName: "Raj (Receptionist)",
    description: "Token #7 placed on hold — patient stepped away",
    createdAt: `${today}T10:20:00`,
    clinicId: "clinic-001",
  },
  {
    id: "aud-006",
    action: "PRESCRIPTION_FINALIZED",
    entityType: "Prescription",
    entityId: "rx-001",
    performedBy: "doctor-001",
    performedByName: "Dr. Sarah Chen",
    description: "Prescription finalized and signed for Priya Nair",
    createdAt: `${today}T09:18:00`,
    clinicId: "clinic-001",
  },
  {
    id: "aud-007",
    action: "DOCTOR_CREATED",
    entityType: "Doctor",
    entityId: "doctor-003",
    performedBy: "receptionist-001",
    performedByName: "Raj (Receptionist)",
    description: "New doctor profile created for Dr. Maya Johnson",
    createdAt: "2025-06-01T09:00:00",
    clinicId: "clinic-001",
  },
  {
    id: "aud-008",
    action: "APPOINTMENT_CANCELLED",
    entityType: "Appointment",
    entityId: "appt-006",
    performedBy: "receptionist-001",
    performedByName: "Raj (Receptionist)",
    description: "Appointment cancelled for Deepa Krishnan",
    createdAt: `${today}T08:00:00`,
    clinicId: "clinic-001",
  },
];

// ─── Stats ────────────────────────────────────────────────────────────────────
export const dashboardStats = {
  today: {
    totalTokens: 54,
    completed: 38,
    waiting: 9,
    onHold: 2,
    abandoned: 3,
    revenue: 42800,
    newPatients: 6,
    avgWaitTime: 18,
  },
  revenueByDay: [
    { day: "Mon", revenue: 38500 },
    { day: "Tue", revenue: 45200 },
    { day: "Wed", revenue: 41800 },
    { day: "Thu", revenue: 52300 },
    { day: "Fri", revenue: 48700 },
    { day: "Sat", revenue: 42800 },
  ],
  tokensByHour: [
    { hour: "8am", tokens: 8 },
    { hour: "9am", tokens: 14 },
    { hour: "10am", tokens: 12 },
    { hour: "11am", tokens: 10 },
    { hour: "12pm", tokens: 7 },
    { hour: "2pm", tokens: 3 },
  ],
  bySpecialization: [
    { name: "Cardiology", value: 22, color: "#00d4ff" },
    { name: "General Medicine", value: 18, color: "#00e5a0" },
    { name: "Pediatrics", value: 14, color: "#a78bfa" },
  ],
  doctorAnalytics: [
    { doctor: "Dr. Chen", patients: 18, revenue: 18400, avgTime: 15 },
    { doctor: "Dr. Patel", patients: 24, revenue: 14800, avgTime: 12 },
    { doctor: "Dr. Johnson", patients: 12, revenue: 9600, avgTime: 20 },
  ],
};

// ─── Medicines Library ─────────────────────────────────────────────────────────
export const medicinesLibrary = [
  { name: "Paracetamol 500mg", category: "Analgesic", commonDosage: "1-1-1", commonDuration: "5 days" },
  { name: "Paracetamol 650mg", category: "Analgesic", commonDosage: "1-1-1", commonDuration: "5 days" },
  { name: "Ibuprofen 400mg", category: "NSAID", commonDosage: "1-1-1", commonDuration: "5 days" },
  { name: "Amoxicillin 500mg", category: "Antibiotic", commonDosage: "1-1-1", commonDuration: "7 days" },
  { name: "Azithromycin 500mg", category: "Antibiotic", commonDosage: "1-0-0", commonDuration: "5 days" },
  { name: "Cetirizine 10mg", category: "Antihistamine", commonDosage: "0-0-1", commonDuration: "7 days" },
  { name: "Pantoprazole 40mg", category: "PPI", commonDosage: "1-0-0", commonDuration: "14 days" },
  { name: "Pan-D capsule", category: "PPI+Domperidone", commonDosage: "1-0-0", commonDuration: "14 days" },
  { name: "Metformin 500mg", category: "Antidiabetic", commonDosage: "1-0-1", commonDuration: "30 days" },
  { name: "Metformin 1000mg", category: "Antidiabetic", commonDosage: "1-0-1", commonDuration: "30 days" },
  { name: "Telmisartan 40mg", category: "Antihypertensive", commonDosage: "1-0-0", commonDuration: "30 days" },
  { name: "Amlodipine 5mg", category: "CCB", commonDosage: "0-0-1", commonDuration: "30 days" },
  { name: "Atorvastatin 10mg", category: "Statin", commonDosage: "0-0-1", commonDuration: "30 days" },
  { name: "Atorvastatin 20mg", category: "Statin", commonDosage: "0-0-1", commonDuration: "30 days" },
  { name: "Warfarin 5mg", category: "Anticoagulant", commonDosage: "0-0-1", commonDuration: "30 days" },
  { name: "Carvedilol 12.5mg", category: "Beta-blocker", commonDosage: "1-0-1", commonDuration: "30 days" },
  { name: "Levothyroxine 50mcg", category: "Thyroid", commonDosage: "1-0-0", commonDuration: "30 days" },
  { name: "Salbutamol inhaler", category: "Bronchodilator", commonDosage: "As needed", commonDuration: "1 month" },
  { name: "Montelukast 10mg", category: "Leukotriene antagonist", commonDosage: "0-0-1", commonDuration: "30 days" },
  { name: "Calpol 250mg syrup", category: "Pediatric Analgesic", commonDosage: "5ml-5ml-5ml", commonDuration: "5 days" },
];

// ─── Users for auth ───────────────────────────────────────────────────────────
export const authUsers = {
  patients: [{ ...patients[0], password: "patient123", role: "patient" as const }],
  doctors: [
    { ...doctors[0], password: "doctor123", role: "doctor" as const },
    { ...doctors[1], password: "doctor456", role: "doctor" as const },
    { ...doctors[2], password: "doctor789", role: "doctor" as const },
  ],
  receptionists: [
    {
      id: "receptionist-001",
      name: "Raj Kumar",
      phone: "9000000003",
      password: "recep123",
      role: "receptionist" as const,
      clinicId: "clinic-001",
    },
  ],
};
